### PR TITLE
Update cargo-zigbuild to 0.8.6

### PR DESCRIPTION
**Pull request by messense**
Always enable zig linker

### CODE REVIEW

**Comment by calavera** [comment]
I still see the GLIBC errors with this change merged into main. I'm going to investigate if it's actually enabling that feature:

```
{
    "events": [
        {
            "timestamp": 1651026072927,
            "message": "/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/bootstrap)\n",
            "ingestionTime": 1651026073022
        },
        {
            "timestamp": 1651026072974,
            "message": "START RequestId: ec4847da-b45c-4270-993d-76c4684b962a Version: $LATEST\n",
            "ingestionTime": 1651026073053
        },
        {
            "timestamp": 1651026072998,
            "message": "/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/bootstrap)\n",
            "ingestionTime": 1651026073053
        },
        {
            "timestamp": 1651026073018,
            "message": "END RequestId: ec4847da-b45c-4270-993d-76c4684b962a\n",
            "ingestionTime": 1651026073053
        },
        {
            "timestamp": 1651026073018,
            "message": "REPORT RequestId: ec4847da-b45c-4270-993d-76c4684b962a\tDuration: 43.46 ms\tBilled Duration: 44 ms\tMemory Size: 128 MB\tMax Memory Used: 3 MB\t\nXRAY TraceId: 1-6268a898-515a4ec6206f55267f6d6cc9\tSegmentId: 7d47be6a1ff2c785\tSampled: true\t\n",
            "ingestionTime": 1651026073053
        },
        {
            "timestamp": 1651026073018,
            "message": "RequestId: ec4847da-b45c-4270-993d-76c4684b962a Error: Runtime exited with error: exit status 1\nRuntime.ExitError\n",
            "ingestionTime": 1651026073053
        }
    ],
    "nextForwardToken": "f/36819111770505033511182159394043767954835951450164625412/s",
    "nextBackwardToken": "b/36819111768475665698115872688126509552136383326053138432/s"
}
```

**Comment by calavera** [comment]
@messense the problem is that this conditional is never satisfied if you try to build for linux x86_64 in a linux x86_64 box:

```
// we only setup zig as linker when target isn't exactly the same as host target
if host_target != raw_target {
```

https://github.com/messense/cargo-zigbuild/blob/main/src/build.rs#L188-L189

And the build flags to enabled `target-applies-to-host` are never applied.

I'm not super familar with all the cases covered in that code, so I didn't send a PR to remove that condition because I don't want to break something else by accident.

**Comment by messense** [comment]
Updated to 0.8.6, please give it a try.

I'll recommend set a target libc version to match AWS lambda runtime environment, see also https://github.com/rnag/rust.aws-cdk-lambda/issues/6.

**Review by calavera — APPROVED** [review]
This worked, awesome job!

**Pull request merged**
